### ISSUE TITLE
why do boolean comparisons with Py object return  Py object?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/PythonCall.jl#294]
First time I am trying to use pythoncall support for defining python classes. Apparently all input arguments as well as self attributes get wrapped in Py.

This is also truth for boolean comparisons like == or != Which return Py objects.

This is difficult as we cannot simply use standard comparisons in if else && or ||, but instead need to wrap everything in Bool(...) In order to get a Julia boolean

What is the purpose of this extra complication? Wouldn't it be much easier if such boolean operators return Julia Bool values?

**Comment by cjdoris** [comment]
This is because Python boolean operators do not always return booleans. For example, comparing two numpy arrays will return an array of booleans.

Some options:
- Call `pytruth` (or `Bool`) as you already do.
- Call `pyeq(Bool, x, y)`, which is equivalent to `pytruth(x == y)` (and similar for other comparisons).
- Call `isequal(x, y)`, which is equivalent to the above too.

**Comment by schlichtanders** [comment]
Thank you for the explanation. Would it be possible to nevertheless return a Julia `Bool` if a standard Boolean was returned?
I think this would massively simplifiy writing Py classes from Julia (for the initially stated reasons)
