### ISSUE TITLE
Support for Multi-Threading with PythonCall?

### ISSUE THREAD

**Issue by nic-barbara** [JuliaPy/PythonCall.jl#330]
Are there any plans to support multi-threading with `PythonCall.jl` in the near future? Almost everything about this package is superior to `PyCall.jl` except for thread safety.

Specifically, it would be great (and in my case - is essential) to be able to call python functions on many threads in parallel. This is useful when a core routine is written in python and needs to be called many time independently. 

For example, some environments in [`ReinforcementLearning.jl`](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl) rely on the python bindings to [MuJoCo](https://mujoco.readthedocs.io/en/stable/overview.html). Evaluating these environments efficiently requires multi-threading (eg: [this implementation](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/72d67668f52ea45e90ee79b0a3a33055cce8cef7/src/ReinforcementLearningZoo/src/algorithms/policy_gradient/multi_thread_env.jl) with `PyCall.jl`), which is currently impossible in `PythonCall`.

Is this something you would consider supporting in the near future?

**Comment by cjdoris** [comment]
Because of the GIL, Python itself has poor support for multithreading, because only one thread can hold the GIL at a time, and this is required to do anything Pythonic. Hence multithreading is only useful in Python if you are doing a lot of work which can release the GIL (such as IO or long-running numerical routines written in C).

In general, if you want to parallelise Python it's generally better to use multiprocessing instead of multithreading. So there are no plans for PythonCall to support it.
